version: 2
updates:
  # Enable version updates for npm (pnpm)
  - package-ecosystem: "npm"
    directory: "/footsteps-web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "willhs"
    commit-message:
      prefix: "chore"
      include: "scope"
    
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/footsteps-web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"